### ISSUE TITLE
checkboxes

### ISSUE THREAD

**Issue by bkeepers** [github-slack/html-to-mrkdwn#1]
These could be translated into real unicode characters like ☐ and ☑︎.

<img width="624" alt="slack_-_github" src="https://user-images.githubusercontent.com/173/33521177-64891a60-d790-11e7-9e9f-8e1c6b098132.png">

**Comment by JasonEtco** [comment]
Dope - you could also use some slackmojis (some combination of `:square:`s). The only reason I bring this up as an alternative is I'm not sure how well Unicodes will work cross-OS. Here's what the above comment looks like on my PC:
![image](https://user-images.githubusercontent.com/10660468/33522258-3c21a2ec-d7b6-11e7-8ec1-9fc9acd7ad50.png)

Happy to test this out with you if you'd like.

**Comment by bkeepers** [comment]
@JasonEtco Sorry, didn't see your comment here before I pushed the fix. Feel free to try different characters/slackmojis here: https://github.com/github-slack/html-to-mrkdwn/blob/42bc01857a33a9e18ee66595d8f4c097cb5056eb/lib/rules.js#L29
